services:
  - type: web
    name: bedoui-backend
    env: docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: PDF_STORAGE_PATH
        value: /app/generated-pdfs
      - key: PDF_TEMPLATE_PATH
        value: /app/templates/devis-pdf.ejs
    disk:
      name: pdf-storage
      mountPath: /app/generated-pdfs
      sizeGB: 1
      
      # Company Information
      - key: COMPANY_NAME
        value: "Bedouielec"
      - key: COMPANY_SIRET
        value: "12345678900001"
      - key: COMPANY_APE
        value: "4321A"
      - key: COMPANY_TVA
        value: "0.20"
      - key: COMPANY_ADDRESS
        value: "Rue Example, 1234 Ville"
      - key: COMPANY_PHONE
        value: "+216 12 345 678"
      - key: COMPANY_EMAIL
        value: "firassmrabett111@gmail.com"
      - key: COMPANY_SITE
        value: "https://bedouistoreproducts.vercel.app"
      - key: COMPANY_LOGO_URL
        value: "https://bedouistoreproducts.vercel.app/logo.png"
